### ISSUE TITLE
Feature Request: Github Support

### ISSUE THREAD

**Issue by Kickball** [thatarchguy/jenkins-ci-hud#1]
I am unsure as to if the current HUD supports Github repos, but it would be a good feature.

**Comment by thatarchguy** [comment]
It would work fine with github repos. It all just depends on what plugin you use on Jenkins. The gitlab plugin for Jenkins creates the gitlabSourceBranch & gitlabTargetBranch parameters. So you'd have to just edit that to what the github plugin uses.

**Comment by Kickball** [comment]
Sounds good, thanks!
